import { describe, expect, test } from "vitest";
import {
  deterministicDriftCenterServer,
  generatePowerUpsServer,
  interpolateZoneCenterServer,
} from "../src/powerUpSpawn";
import { Timestamp } from "firebase-admin/firestore";

// Golden vectors. Same input/output table lives verbatim in:
//   ios/PoulePartyTests/ParityGoldenTests.swift
//   android/app/src/test/.../ParityGoldenTest.kt
//
// If a change here fails on one platform but not the others, parity is broken
//, don't silence it, fix the divergence. Values were generated by the TS
// reference impl; Swift and Kotlin must match bit-for-bit up to the tolerances
// each test declares (geo math is double-precision, so we compare with 1e-9
// tolerance, exact equality would fail on cross-platform fp differences we
// can live with).

const TOL = 1e-9;

// ─── interpolateZoneCenter ────────────────────────────────────

describe("parity, interpolateZoneCenter", () => {
  test("50% progress", () => {
    const out = interpolateZoneCenterServer(
      { latitude: 50.85, longitude: 4.35 },
      { latitude: 50.87, longitude: 4.37 },
      1500,
      750,
    );
    expect(out.latitude).toBeCloseTo(50.86, 10);
    expect(out.longitude).toBeCloseTo(4.36, 10);
  });

  test("missing finalCenter returns initial", () => {
    const out = interpolateZoneCenterServer(
      { latitude: 50.85, longitude: 4.35 },
      undefined,
      1500,
      750,
    );
    expect(out.latitude).toBeCloseTo(50.85, 10);
    expect(out.longitude).toBeCloseTo(4.35, 10);
  });

  test("zero progress returns final", () => {
    const out = interpolateZoneCenterServer(
      { latitude: 48.8, longitude: 2.3 },
      { latitude: 48.9, longitude: 2.4 },
      2000,
      0,
    );
    expect(out.latitude).toBeCloseTo(48.9, 10);
    expect(out.longitude).toBeCloseTo(2.4, 10);
  });

  test("full progress (currentRadius == initialRadius) returns initial", () => {
    const out = interpolateZoneCenterServer(
      { latitude: 50.85, longitude: 4.35 },
      { latitude: 50.9, longitude: 4.4 },
      1500,
      1500,
    );
    expect(out.latitude).toBeCloseTo(50.85, 10);
    expect(out.longitude).toBeCloseTo(4.35, 10);
  });
});

// ─── deterministicDriftCenter ─────────────────────────────────

describe("parity, deterministicDriftCenter", () => {
  test("seed 12345, 1500→1400", () => {
    const out = deterministicDriftCenterServer(
      { latitude: 50.85, longitude: 4.35 },
      1500,
      1400,
      12345,
    );
    expect(out.latitude).toBeCloseTo(50.849704286836015, TOL);
    expect(out.longitude).toBeCloseTo(4.349626765727747, TOL);
  });

  test("seed 42, 2000→1800", () => {
    const out = deterministicDriftCenterServer(
      { latitude: 48.8, longitude: 2.3 },
      2000,
      1800,
      42,
    );
    expect(out.latitude).toBeCloseTo(48.800889182782186, TOL);
    expect(out.longitude).toBeCloseTo(2.3001280811249516, TOL);
  });

  test("newRadius == 0 returns basePoint", () => {
    const out = deterministicDriftCenterServer(
      { latitude: 50.85, longitude: 4.35 },
      500,
      0,
      7,
    );
    expect(out.latitude).toBeCloseTo(50.85, 10);
    expect(out.longitude).toBeCloseTo(4.35, 10);
  });

  test("oldRadius == newRadius returns basePoint", () => {
    const out = deterministicDriftCenterServer(
      { latitude: 50.85, longitude: 4.35 },
      1500,
      1500,
      12345,
    );
    expect(out.latitude).toBeCloseTo(50.85, 10);
    expect(out.longitude).toBeCloseTo(4.35, 10);
  });
});

// ─── generatePowerUps ─────────────────────────────────────────

describe("parity, generatePowerUps", () => {
  test("batch 1, count 3, seed 12345", () => {
    const out = generatePowerUpsServer(
      { latitude: 50.85, longitude: 4.35 },
      1500,
      3,
      12345,
      1,
      ["invisibility", "zoneFreeze", "radarPing"],
      Timestamp.fromMillis(0),
    );
    expect(out).toHaveLength(3);

    expect(out[0].id).toBe("pu-1-0-371690");
    expect(out[0].type).toBe("radarPing");
    expect(out[0].location.latitude).toBeCloseTo(50.85167604533923, TOL);
    expect(out[0].location.longitude).toBeCloseTo(4.36041475997135, TOL);

    expect(out[1].id).toBe("pu-1-1-371817");
    expect(out[1].type).toBe("invisibility");
    expect(out[1].location.latitude).toBeCloseTo(50.84442779979479, TOL);
    expect(out[1].location.longitude).toBeCloseTo(4.356573765300285, TOL);

    expect(out[2].id).toBe("pu-1-2-371944");
    expect(out[2].type).toBe("zoneFreeze");
    expect(out[2].location.latitude).toBeCloseTo(50.84439414095354, TOL);
    expect(out[2].location.longitude).toBeCloseTo(4.344395523809516, TOL);
  });

  test("reversing enabledTypes reshuffles assigned types (order is authoritative)", () => {
    // Same seed as above, same positions, but enabledTypes in the opposite
    // order → types at each index must differ. If one platform drifts back
    // to enum-order filtering, this test fails loudly.
    const out = generatePowerUpsServer(
      { latitude: 50.85, longitude: 4.35 },
      1500,
      3,
      12345,
      1,
      ["radarPing", "zoneFreeze", "invisibility"],
      Timestamp.fromMillis(0),
    );
    expect(out.map((p) => p.type)).toEqual(["invisibility", "radarPing", "zoneFreeze"]);
  });

  test("single-type enabledTypes assigns the same type to every spot", () => {
    const out = generatePowerUpsServer(
      { latitude: 50.85, longitude: 4.35 },
      1500,
      3,
      12345,
      1,
      ["invisibility"],
      Timestamp.fromMillis(0),
    );
    expect(out.map((p) => p.type)).toEqual(["invisibility", "invisibility", "invisibility"]);
  });

  test("count 0 returns empty", () => {
    const out = generatePowerUpsServer(
      { latitude: 0, longitude: 0 },
      1500,
      0,
      12345,
      1,
      ["invisibility"],
      Timestamp.fromMillis(0),
    );
    expect(out).toEqual([]);
  });

  test("empty enabledTypes returns empty (nothing to assign)", () => {
    const out = generatePowerUpsServer(
      { latitude: 0, longitude: 0 },
      1500,
      5,
      12345,
      1,
      [],
      Timestamp.fromMillis(0),
    );
    expect(out).toEqual([]);
  });

  test("negative driftSeed, batch 0 (initial spawn) is stable", () => {
    const out = generatePowerUpsServer(
      { latitude: 50.85, longitude: 4.35 },
      1500,
      2,
      -1,
      0,
      ["invisibility", "radarPing"],
      Timestamp.fromMillis(0),
    );
    expect(out[0].id).toBe("pu-0-0-31");
    expect(out[0].type).toBe("radarPing");
    expect(out[0].location.latitude).toBeCloseTo(50.85543657219541, TOL);
    expect(out[0].location.longitude).toBeCloseTo(4.3525392519978965, TOL);

    expect(out[1].id).toBe("pu-0-1-96");
    expect(out[1].type).toBe("invisibility");
    expect(out[1].location.latitude).toBeCloseTo(50.85637613935454, TOL);
    expect(out[1].location.longitude).toBeCloseTo(4.362005903305925, TOL);
  });
});

// ─── interpolate edge cases ──────────────────────────────────

describe("parity, interpolate edges", () => {
  test("currentRadius > initialRadius clamps to initialCenter (no negative progress)", () => {
    // Progress would be negative → clamped to 0 → returns initialCenter.
    const out = interpolateZoneCenterServer(
      { latitude: 50.85, longitude: 4.35 },
      { latitude: 50.87, longitude: 4.37 },
      1500,
      2000,
    );
    expect(out.latitude).toBeCloseTo(50.85, 10);
    expect(out.longitude).toBeCloseTo(4.35, 10);
  });

  test("initialRadius 0 returns initialCenter (guard)", () => {
    const out = interpolateZoneCenterServer(
      { latitude: 50.85, longitude: 4.35 },
      { latitude: 50.9, longitude: 4.4 },
      0,
      0,
    );
    expect(out.latitude).toBeCloseTo(50.85, 10);
    expect(out.longitude).toBeCloseTo(4.35, 10);
  });
});

// ─── drift edge cases ────────────────────────────────────────

describe("parity, drift edges", () => {
  test("big shrink (2000→500)", () => {
    const out = deterministicDriftCenterServer(
      { latitude: 50.85, longitude: 4.35 },
      2000,
      500,
      777,
    );
    expect(out.latitude).toBeCloseTo(50.849217523608516, TOL);
    expect(out.longitude).toBeCloseTo(4.34728423145545, TOL);
  });

  test("negative seed", () => {
    const out = deterministicDriftCenterServer(
      { latitude: 50.85, longitude: 4.35 },
      1500,
      1400,
      -99,
    );
    expect(out.latitude).toBeCloseTo(50.85023537723916, TOL);
    expect(out.longitude).toBeCloseTo(4.350282673772987, TOL);
  });
});
